export type AutoCapitalizeOptions =
  | "none"
  | "sentences"
  | "words"
  | "characters";

export type TextInputAutoComplete =
  | "off"
  | "name"
  | "username"
  | "email"
  | "password"
  | "new-password"
  | "current-password"
  | "one-time-code"
  | "tel"
  | "postal-code"
  | "street-address"
  | "cc-number"
  | "cc-exp"
  | "cc-csc"
  | "gender"
  | "birthdate-full"
  | "organization"
  | "url"
  | undefined;

export type TextInputContentType =
  | "none"
  | "URL"
  | "addressCity"
  | "addressCityAndState"
  | "addressState"
  | "countryName"
  | "creditCardNumber"
  | "creditCardExpiration"
  | "emailAddress"
  | "familyName"
  | "fullStreetAddress"
  | "givenName"
  | "jobTitle"
  | "location"
  | "middleName"
  | "name"
  | "namePrefix"
  | "nameSuffix"
  | "nickname"
  | "organizationName"
  | "postalCode"
  | "streetAddressLine1"
  | "streetAddressLine2"
  | "sublocality"
  | "telephoneNumber"
  | "username"
  | "password"
  | "newPassword"
  | "oneTimeCode"
  | undefined;
